# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5000
@host={{hostname}}:{{port}}

POST http://{{hostname}}:{{port}}/cadastro/clientes
Content-Type: application/json

{
    "cpf": "12345678909",
    "nome": "Felipe Azevedo",
    "telefone": "11912345678",
    "email": "felipe@azevedo.com",
    "enderecos": [
        {
            "cep": "01234567"
        }
    ]
}

###

GET http://{{hostname}}:{{port}}/cadastro/clientes

###

GET http://{{hostname}}:{{port}}/cadastro/clientes/12345678909